name: variables
on: push
env:
 root_env_variable: Hi!!!ðŸ˜ƒ
 
jobs:
  job_1:
   runs-on: ubuntu-latest
   env:
    job_env_variable: Good Morning ðŸŒ„
   steps:
   - name: "JOB1"
     run: echo "$root_env_variable $First_Name $job_env_variable"
     env:
       First_Name: user1
 
